### ISSUE TITLE
Question: How can I use this to pipe a WebRTC MediaStream to the renderer?

### ISSUE THREAD

**Issue by derwaldgeist** [audio-lab/render#1]
Since the sample is based on an artificial Generator, I am wondering how I can convert a WebRTC MediaStream (returned by getUserMedia) into an input stream capable of piping into the renderer?

**Comment by dy** [comment]
Hi @derwaldgeist!
This project is going to be deprecated, please use web audio API for processing MediaStream, like [here](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaStreamSource)

**Comment by derwaldgeist** [comment]
Thanks for your super-fast reply! Does WebAudio provide similar FFT capabilities?

**Comment by dy** [comment]
Yes, there is AudioAnalyzerNode
